apiVersion: v1
kind: Namespace
metadata:
  name: btc-shopflow
  labels:
    name: btc-shopflow
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: btc-shopflow-dev
  labels:
    name: btc-shopflow-dev
    environment: development
